name: Run integration tests in NodeJS

on: [push, pull_request]

jobs:
  run-tests:
    name: "run integration tests"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install environment
      run: npm install

    - name: run tests
      run: npm test
      env:
        CI: true
